namespace ProjectBabbleNeos
{
    public static class BabbleExpressions
    {
        public static string[] MouthShapesWithAddress = new string[]
        {
            "/cheekPuff",
            "/cheekSquintLeft",
            "/cheekSquintRight",
            "/noseSneerLeft",
            "/noseSneerRight",
            "/jawOpen",
            "/jawForward",
            "/jawLeft",
            "/jawRight",
            "/mouthFunnel",
            "/mouthPucker",
            "/mouthLeft",
            "/mouthRight",
            "/mouthRollUpper",
            "/mouthRollLower",
            "/mouthShrugUpper",
            "/mouthShrugLower",
            "/mouthClose",
            "/mouthSmileLeft",
            "/mouthSmileRight",
            "/mouthFrownLeft",
            "/mouthFrownRight",
            "/mouthDimpleLeft",
            "/mouthDimpleRight",
            "/mouthUpperUpLeft",
            "/mouthUpperUpRight",
            "/mouthLowerDownLeft",
            "/mouthLowerDownRight",
            "/mouthPressLeft",
            "/mouthPressRight",
            "/mouthStretchLeft",
            "/mouthStretchRight",
            "/tongueOut",
        };
    }
}
