namespace ProjectBabbleNeos
{
    public static class BabbleExpressions
    {
        public static string[] MouthShapesWithAddress = new string[]
        {
            "/cheekPuff",
            "/cheekSquint_L",
            "/cheekSquint_R",
            "/noseSneer_L",
            "/noseSneer_R",
            "/jawOpen",
            "/jawForward",
            "/jawLeft",
            "/jawRight",
            "/mouthFunnel",
            "/mouthPucker",
            "/mouthLeft",
            "/mouthRight",
            "/mouthRollUpper",
            "/mouthRollLower",
            "/mouthShrugUpper",
            "/mouthShrugLower",
            "/mouthClose",
            "/mouthSmile_L",
            "/mouthSmile_R",
            "/mouthFrown_L",
            "/mouthFrown_R",
            "/mouthDimple_L",
            "/mouthDimple_R",
            "/mouthUpperUp_L",
            "/mouthUpperUp_R",
            "/mouthLowerDown_L",
            "/mouthLowerDown_R",
            "/mouthPress_L",
            "/mouthPress_R",
            "/mouthStretch_L",
            "/mouthStretch_R",
            "/tongueOut",
        };
    }
}
